let jokes = [
	"What falls, but never needs a bandage? The rain.",
	"I was going to tell you a joke about boxing but I forgot the punch line.",
	"I'm not a fan of spring cleaning. Let's be honest, I'm not into summer, fall, or winter cleaning either.",
	"Why did the egg hide? It was a little chicken.",
	"What did the dirt say to the rain? If you keep this up, my name will be mud!",
	"Why couldn't the sunflower ride its bike? It lost its petals.",
	"What's an egg's favorite vacation spot? New Yolk City.",
	"I ate a sock yesterday. It was very time-consuming.",
	"What kind of candy do astronauts like? Mars bars.",
	"I wanted to buy some camo pants but couldn't find any.",
	"Why don't scientists trust atoms? Because they make up everything!",
	"What do you call fake spaghetti? An impasta!",
	"Why don't skeletons fight each other? They don't have the guts!",
	"Why did the scarecrow win an award? Because he was outstanding in his field!",
	"Why did the bicycle fall over? It was two-tired!",
	"Why don't melons get married? Because they cantaloupe!",
	"What do you call a bear with no teeth? A gummy bear!",
	"What did the man say to his fingers? I'm counting on you.",
	"How does the ocean say hello? It waves.",
	"Humpty Dumpty had a great fall. Summer wasn't bad either.",
	"How do pigs do their homework? With a pigpen.",
	"How do you hire a horse? Put it on a ladder.",
	"What do pigs use in the shower? Hogwash.",
	"How do you fix a broken tomato? With tomato paste.",
	"What's the pirate's favorite letter? The 'C'.",
	"What's the best way to plan a party in space? You planet.",
	"What kind of tree fits in your hand? A palm tree.",
	"What kind of witch goes to the beach? A sandwich.",
	"What has four wheels and flies? A garbage truck.",
	"Why did the sauna go to the doctor? It wasn't feeling so hot.",
	"Why did the owl quit its job? It didn't give a hoot.",
	"How much do dead batteries cost? There should be no charge.",
	"Did you hear about the soap-stealing robber? He decided to come clean.",
	"I used to be afraid of painting, but eventually I brushed it off.",
	"Why don't people play more hide-and-seek? Because good players are hard to find.",
	"What did one eye say to the other? Between us, something smells.",
	"Why are astronauts so clean? They take meteor showers.",
	"When is a door not a door? When it's ajar.",
	"What did the hamburgers name their new baby? Patty.",
	"One did the T-rex say to the velociraptor? Nothing, they're extinct.",
	"Why shouldn't you trust jungle animals? They're always lion.",
	"What's the best way to make an egg roll? Push it.",
	"Why did the leaf go to the doctor? It had a bad fall.",
	"How do you make a squid laugh? Give it ten-tickles.",
	"I childproofed my house. Somehow they still got in.",
	"I just read that someone in London gets stabbed every 52 seconds. Poor guy.",
	"What's red and bad for your teeth? A brick.",
	"The guy who stole my diary just died. My thoughts are with his family.",
	"Today, I asked my phone 'Alexa, why am I still single?' and it activated the front camera.",
	"Why don't cannibals eat clowns? Because they taste funny.",
	"Want to hear a construction joke? Oh never mind, I'm still working on that one.",
	"Why don't scientists trust atoms? Because they make up everything.",
	"I poured root beer in a square glass. Now I just have beer.",
	"What did the bald man exclaim when he received a comb for a present? Thanks—I'll never part with it.",
	"Rest in peace, boiling water. You will be mist.",
	"Have you heard about the new restaurant called Karma? There's no menu: You get what you deserve.",
	"How does a rabbi make coffee? Hebrews it.",
	"Why can't male ants sink? They're buoy-ant.",
	"What is an astronaut's favorite part on a computer? The space bar.",
	"What's a private investigator's favorite shoe? Sneak-ers.",
	"Why don't scientists trust atoms? Because they make up everything!",
	"How do you organize a space party? You planet!",
	"I used to be a baker, but I couldn't make enough dough.",
	"Why did the scarecrow win an award? Because he was outstanding in his field!",
	"Why don't skeletons fight each other? They don't have the guts.",
	"What did one wall say to the other wall? 'I'll meet you at the corner!'",
	"Why don't scientists trust stairs? Because they're always up to something.",
	"Why did the tomato turn red? Because it saw the salad dressing!",
	"What do you get when you cross a snowman and a shark? Frostbite!",
	"What did one wall say to the other? I'll meet you at the corner!",
	"Why did the chicken cross the playground? To get to the other slide!",
	"How do you make a tissue dance? Put a little boogey in it!",
	"Why did the cookie go to the doctor? Because it was feeling crumbly.",
	"What do you get when you cross a sheep and a kangaroo? A woolly jumper.",
	"Why did the chicken go to outer space? To lay an egg on the moon!",
	"What do you get when you cross a cow and a duck? Milk and quackers!",
	"Why don't scientists trust atoms? Because they make up everything!",
	"What do you call a fake noodle? An impasta!",
	"What do you get when you cross a snowman and a vampire? Frostbite.",
	"Why do programmers prefer dark mode? Because light attracts bugs.",
	"Debugging: Being the detective in a crime movie where you’re also the murderer.",
	"There are only 10 types of people in the world: those who understand binary, and those who don’t.",
	"Real programmers don’t comment their code. If it was hard to write, it should be hard to understand.",
	"My code doesn’t always work, but when it does, I don’t know why."
];


function gjoke() {
	let index = Math.floor(Math.random() * jokes.length);
	let jokeElement = document.getElementById("joke");
	jokeElement.innerHTML = jokes[index];
}                     
